In [42]:
import pandas as pd
import numpy as np

In [43]:
df = pd.read_csv("data.csv")
df

number_people                       date  timestamp  day_of_week  \
0                 37  2015-08-14 17:00:11-07:00      61211            4   
1                 45  2015-08-14 17:20:14-07:00      62414            4   
2                 40  2015-08-14 17:30:15-07:00      63015            4   
3                 44  2015-08-14 17:40:16-07:00      63616            4   
4                 45  2015-08-14 17:50:17-07:00      64217            4   
...              ...                        ...        ...          ...   
62179             23  2017-03-18 18:42:28-07:00      67348            5   
62180             21  2017-03-18 18:52:35-07:00      67955            5   
62181             25  2017-03-18 19:02:40-07:00      68560            5   
62182             18  2017-03-18 19:12:47-07:00      69167            5   
62183             23  2017-03-18 19:22:51-07:00      69771            5   

       is_weekend  is_holiday  temperature  is_start_of_semester  \
0               0           0        71.76                     0   
1               0           0        71.76                     0   
2               0           0        71.76                     0   
3               0           0        71.76                     0   
4               0           0        71.76                     0   
...           ...         ...          ...                   ...   
62179           1           0        61.07                     0   
62180           1           0        61.07                     0   
62181           1           0        56.71                     0   
62182           1           0        56.71                     0   
62183           1           0        56.71                     0   

       is_during_semester  month  hour  
0                       0      8    17  
1                       0      8    17  
2                       0      8    17  
3                       0      8    17  
4                       0      8    17  
...                   ...    ...   ...  
62179                   1      3    18  
62180                   1      3    18  
62181                   1      3    19  
62182                   1      3    19  
62183                   1      3    19  

[62184 rows x 11 columns]

In [44]:
X = df.iloc[:, 3:-1].values
y = df.iloc[:, 0].values
print(X)

[[4. 0. 0. ... 0. 0. 8.]
 [4. 0. 0. ... 0. 0. 8.]
 [4. 0. 0. ... 0. 0. 8.]
 ...
 [5. 1. 0. ... 0. 1. 3.]
 [5. 1. 0. ... 0. 1. 3.]
 [5. 1. 0. ... 0. 1. 3.]]


In [45]:
print(y)

[37 45 40 ... 25 18 23]


In [46]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
Ct1 = ColumnTransformer([('encoder', OneHotEncoder(), [0])], remainder = 'passthrough')
X = Ct1.fit_transform(X)

In [47]:
pd.DataFrame(X)

0    1    2    3    4    5    6    7    8      9    10   11   12
0      0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  71.76  0.0  0.0  8.0
1      0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  71.76  0.0  0.0  8.0
2      0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  71.76  0.0  0.0  8.0
3      0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  71.76  0.0  0.0  8.0
4      0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  71.76  0.0  0.0  8.0
...    ...  ...  ...  ...  ...  ...  ...  ...  ...    ...  ...  ...  ...
62179  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  61.07  0.0  1.0  3.0
62180  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  61.07  0.0  1.0  3.0
62181  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  56.71  0.0  1.0  3.0
62182  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  56.71  0.0  1.0  3.0
62183  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  56.71  0.0  1.0  3.0

[62184 rows x 13 columns]

In [83]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

In [84]:
from sklearn.neighbors import KNeighborsRegressor
reg = KNeighborsRegressor(n_neighbors=3)
reg.fit(X_train, y_train)

KNeighborsRegressor(n_neighbors=3)

In [85]:
reg.score(X_test, y_test)

0.7709072811222969